/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package connector;

/**
 *
 * @author Divine Calunod
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
public class connector {
     public static Connection getConnection() {
        String url =  "jdbc:mysql://localhost:3306/wawa";
        String username = "root";
        String password = "root";

        try {
            return DriverManager.getConnection(url, username, password);
        } catch (SQLException e) {
            System.out.println("Connection failed: " + e.getMessage());
            return null;
        }
    }
    
    
}
